### ISSUE TITLE
Feature Request: $siegfried -update -deluxe

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#103]
Is there potential to have an -update option that also delivers Tika/Freedesktop signatures? I'd find this very useful for educating folk about alternatives to DROID.

**Comment by richardlehane** [comment]
Hmmm... yes that's a nice idea can do. 

Perhaps offer a few flavours: PRONOM, tika, freedesktop, LOC or the triple threat (PRONOM-tika-loc) which I already publish & use for the "Try Siegfried" service?

No need to do this with another flag, could do like `sf -update tika` or `sf -update loc` or `sf -update pronom-tika-loc`.

Effect of this command would be to overwrite default.sig (so your default.sig might no longer be PRONOM).

**Comment by richardlehane** [comment]
Hey Ross, 
this is in sf 1.7.5 & available now. Details of implementation are in this bit of the changelog...

sf -update flag can now be used to download/update non-PRONOM signatures. Options are "loc", "tika", "freedesktop", "pronom-tika-loc", "deluxe" and "archivematica". To update a non-PRONOM signature, include the signature name as an argument after the flags e.g. sf -update freedesktop. This command will overwrite 'default.sig' (the default signature file that sf loads). You can preserve your default signature file by providing an alternative -sig target e.g. sf -sig notdefault.sig -update loc. If you use one of the signature options as a filename (with or without a .sig extension), you can omit the signature argument i.e. sf -update -sig loc.sig is equivalent to sf -sig loc.sig -update loc. 

I'll update the docs (wiki and homepage) shortly
Rich

**Comment by ross-spencer** [comment]
Brilliant stuff! - Just gave it a go - works a treat!

Thanks Richard,
Ross
