### ISSUE TITLE
How to use fdd/LOC file signatures?

### ISSUE THREAD

**Issue by kieranjol** [richardlehane/siegfried#104]
Hi ,

I'm experimenting with using SF in order to use with the format section of PREMIS within the Irish Film Institute. This is such a great tool! I saw on your website that LOC/FDD is in beta mode. 
Must I download their signature file and specify its usage? I'm not sure how to get it working.
```
sf -version
siegfried 1.7.4
/usr/share/siegfried/default.sig (2017-07-14T15:56:40+10:00)
identifiers: 
  - pronom: DROID_SignatureFile_V90.xml; container-signature-20170330.xml
```

Best,

Kieran.

**Comment by kieranjol** [comment]
NVM, I found the answer on the wiki: http://www.loc.gov/preservation/digital/formats/fdd/fdd_xml_info.shtml

**Comment by richardlehane** [comment]
thanks Kieran - glad to hear you got it sorted. A shortcut for setting up your environment up to build custom signatures is to copy the latest "data.zip" file from the [releases page](https://github.com/richardlehane/siegfried/releases) into your siegfried home dir (described as "Quick setup" here: https://github.com/richardlehane/siegfried/wiki/Building-a-signature-file-with-ROY#setup). This zip file has recent updates for most of the signature types & also has format sets etc. so really has all you need to start building your own signatures.

Also, the next release will include a feature that Ross has requested to make use of non-PRONOM signatures easier (available through `sf -update` and not dependent on using `roy`): https://github.com/richardlehane/siegfried/issues/103

Finally, if you're using with PREMIS you might be interested in this project I saw last week: https://github.com/hvanstappen/Siegfried2Premis - may help with your mappings

cheers
Richard

**Comment by hvanstappen** [comment]
hi Kieran,
the Siegfried2Premis stylesheet is made for the purpose of a specific project/organization, but if you can use it in any way, I'd be happy to hear your comments. You'll probably see that it needs some improvements (my xml skills are rather limited; e.g. I wasn't able to create an xsl that can work on the json directly).
@richardlehane : thanks for mentioning!

best,
Henk

**Comment by kieranjol** [comment]
Hey both,

thanks so much for all that info. the `sf -update` option sounds very
interesting. I'll take another look at Siegfried2Premis, though the json >
XML transform that you use could be useful to share as well?

**Comment by hvanstappen** [comment]
Hi Kieran,

for the JSON > XML transformation I used Catmandu (on Github as well. You'll need to install it's XML library and then use the command:
$ catmandu convert JSON to XML < “path/to/siegfriedout.json” > path/to/siegfriedout.xml 

best,

henk
--
Henk Vanstappen
e: henk@datable.be
m: +32 498 59 68 55
s: henkvanstappen


 <https://www.linkedin.com/in/henkvanstappen>
 <https://www.linkedin.com/in/henkvanstappen>
