### ISSUE TITLE
Update to PRONOM94

### ISSUE THREAD

**Issue by ablwr** [richardlehane/siegfried#122]
Not to rush... but PRONOM 94 was released yesterday and I'm filing an issue to note that Siegfried will need an update as well!

**Comment by ablwr** [comment]
OMG that would be so amazing!!!

**Comment by ablwr** [comment]
I am eager to add it into the next Archivematica release!

**Comment by ablwr** [comment]
Miracle worker!!!!!!!!!!!!!!!!!!!! Thanks!

**Comment by richardlehane** [comment]
no worries, will be great to see an update in archivematica
