### ISSUE TITLE
Error when issuing sf --version

### ISSUE THREAD

**Issue by sebastiandaberdaku** [richardlehane/siegfried#145]
When issuing the command:
```
$sf --version
```
I get the following message:
```
2020/06/28 09:55:54 [FATAL] error loading signature file, got: siegfried: signature file is incompatible with this version of sf; try running `sf -update`
```
I've tried updating with 
```
$sudo sf -update
... downloading latest signature file ...
... writing /usr/share/siegfried/default.sig ...
```
but i keep getting the same error. I have tried this on Ubuntu 18.04.

**Comment by richardlehane** [comment]
Hi Sebastian
many thanks for letting me know. It looks like my auto-deployment scripts have gone awry and the beta for the next release (1.9.0) has been prematurely published. cc @ross-spencer !

To fix you'll need to "downgrade" back to the current stable version, 1.8.0, e.g. by doing:
    sudo apt-get remove siegfried
    sudo apt-get install siegfried=1.8.0-1

I've removed the errant release so you shouldn't get accidentally upgraded again.

Apologies for this mishap,
Richard

**Comment by sebastiandaberdaku** [comment]
Thank you Richard, 

I confirm that "downgrading" to version 1.8.0-1 solves the issue.

Best regards, 

Sebastian

**Comment by ross-spencer** [comment]
oh no! Sorry @richardlehane and @sebastiandaberdaku :scream: 

I'll need to catch up with you Richard to understand what happened, really sorry for the inconvenience, but I'm also glad things are looking good now! :slightly_smiling_face:
