### ISSUE TITLE
Lex Error

### ISSUE THREAD

**Issue by gleporeNARA** [richardlehane/siegfried#147]
Got the following error with the attached xml file created by the PRONOM Signature Development Tool.

sudo roy build -extend David-Hanney-chiptune-v1.0-signature-file.xml dh.sig
2020/08/07 08:14:35 parse error dev/1: Lex error in dev/1: encountered invalid character 'S'

[David-Hanney-chiptune-v1.0-signature-file.zip](https://github.com/richardlehane/siegfried/files/5041279/David-Hanney-chiptune-v1.0-signature-file.zip)

**Comment by richardlehane** [comment]
Hi Greg
I think it's because your sequence has ascii contents rather than hex. Try replacing with "44534E4753455155" and should fix I think
all the best
Richard
