### ISSUE TITLE
Feature request: TEI support ?

### ISSUE THREAD

**Issue by sviscapi** [richardlehane/siegfried#151]
Dear @richardlehane ,

Could it be possible to add TEI support to Siegfried ?

https://tei-c.org/
https://github.com/TEIC

At the moment, PRONOM, which in turns uses DROID, identifies TEI files as plain XML files, which is not correct.

Best regards,

Samuel, from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by sviscapi** [comment]
Hi again,

I understand that Siegfried also uses Wikidata to identify formats. 

There is a TEI entry there:

https://www.wikidata.org/wiki/Q780920

Maybe I was wrong, Siegfried could already be able to tell TEI apart from XML. I need to check though.

Best regards,

Samuel, from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by richardlehane** [comment]
Hi @sviscapi - the latest version of siegfried can use wikidata identifications, but it looks like that wikidata entry currently doesn't have any related signatures (patterns to enable the matching). To get siegfried to identify TEI files, you'd need to get updates to either PRONOM (to create a new entry) or wikidata (to add signatures to the existing entry).

Incidentally it is PRONOM research week at the moment, so somebody might be willing to help with this. I've added a ticket to their github repository: https://github.com/digital-preservation/pronom-research-week/issues/25

**Comment by sviscapi** [comment]
Hi @richardlehane ,

Many thanks for your quick reply and for relaying my question to PRONOM, that's really appreciated.

Best regards,

Samuel, from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by sviscapi** [comment]
Hi @richardlehane , and Happy New Year 🎉 

Would you have any news regarding TEI support in Siegfried ?

Best regards,

Samuel, from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by richardlehane** [comment]
PRONOM v98 update from October last year includes TEI signatures. Update coming shortly

**Comment by sviscapi** [comment]
Hi @richardlehane ,

Thanks for the heads up, really appreciated.

Cheers, Samuel
