### ISSUE TITLE
Hombrew install failed on macOS x v11.1 

### ISSUE THREAD

**Issue by eddycolloton** [richardlehane/siegfried#155]
I received the following error message when trying to install siegfried using homebrew running macOS 11.1:

> % brew install richardlehane/digipres/siegfried
> ==> Tapping richardlehane/digipres
> Cloning into '/usr/local/Homebrew/Library/Taps/richardlehane/homebrew-digipres'...
> remote: Enumerating objects: 27, done.
> remote: Counting objects: 100% (27/27), done.
> remote: Compressing objects: 100% (21/21), done.
> remote: Total 329 (delta 13), reused 19 (delta 6), pack-reused 302
> Receiving objects: 100% (329/329), 58.34 KiB | 2.08 MiB/s, done.
> Resolving deltas: 100% (186/186), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/richardlehane/homebrew-digipres/bagger.rb
> bagger: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
> Please report this issue to the richardlehane/digipres tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/richardlehane/homebrew-digipres/bagger.rb:8
> 
> Error: Cannot tap richardlehane/digipres: invalid syntax in tap!

My apologies if this is simply user error!

**Comment by richardlehane** [comment]
thanks for letting me know Eddy. I've just merged a pull request from Reto Kromer (https://github.com/richardlehane/homebrew-digipres/pull/5) that I hope will fix this issue

**Comment by richardlehane** [comment]
I think this was fixed above, but please re-open if necessary
