### ISSUE TITLE
Does Siegfried identify correctly MapInfo file formats ?

### ISSUE THREAD

**Issue by sviscapi** [richardlehane/siegfried#168]
Dear @richardlehane ,

Does Siegfried identift correctly MapInfo file formats, a GIS application from "Precisely" ?

https://www.precisely.com/product/precisely-mapinfo/mapinfo-pro

https://en.wikipedia.org/wiki/MapInfo_TAB_format
https://en.wikipedia.org/wiki/MapInfo_Interchange_Format

As far as I know, the .DAT files are properly identified as dBase III DBF file, but what about the other file formats (MAP/IND/tab/WOR/MID/MIF) ?

If not, could support for those file formats be added in a future Siegfried version ?

Best regards,

Samuel

**Comment by richardlehane** [comment]
Hi Samuel
siegfried doesn't have any of its own signatures, it implements third-party sources of signatures e.g. PRONOM, mimeinfo, LOC FDD, wikidata. Most users use the PRONOM signatures which are the default.

Assuming you're running siegfried with PRONOM signatures, the best way to check coverage is to [search the PRONOM database](https://www.nationalarchives.gov.uk/PRONOM/Default.aspx). A search for MapInfo gives three possible formats: [x-fmt/225](https://www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=317), [x-fmt/231](https://www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=323) and [fmt/1256](https://www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=2074).

If you are missing particular formats, you can develop your own custom signatures and use the `roy` tool to add them to your own siegfried instance, but the best way to get them included is to lobby for inclusion in whatever third-party source you are using. E.g. to submit to PRONOM go here: [https://www.nationalarchives.gov.uk/contact-us/submit-information-for-pronom/](https://www.nationalarchives.gov.uk/contact-us/submit-information-for-pronom/).

Hope this helps
Richard
