### ISSUE TITLE
Roy expects quotation marks in Droid csv from Siegfried for comparison

### ISSUE THREAD

**Issue by ostnatalie** [richardlehane/siegfried#174]
Hello,
We tried to use Roy for comparing output files from Siegfried and Droid. We were comparing Droid csv output from Siegfried and csv output from using this command:

roy compare file1.csv file2.csv > comparison.csv        

We got this:

“2022/01/05 09:57:39 not a valid results file, bad char 73”   
 
 (file1 is Droid csv from Siegfried, file2 is from Droid)           

We have found out that it was probably caused by the “missing” quotation marks in column names in Droid csv from Siegfried. 

Output from Droid
 ![Droid_output](https://user-images.githubusercontent.com/97174678/148230267-bb6bf932-a513-4436-a2a2-6b49b5d48d07.JPG)

Output from Siegfried
![image](https://user-images.githubusercontent.com/97174678/148230019-479547ae-9ebe-4149-8615-832c5dc21f24.png)

 
When we added the quotation marks to that Siegfried output then Roy carried out the comparison. 

So we are sending this in case it could be useful information, that Roy expects the quotation marks in the Droid csv output from Siegfried. 

We then tried it with JSON output from Siegfried and with normal csv from Siegfried and it worked perfectly.

**Comment by richardlehane** [comment]
thanks for reporting this @ostnatalie - I expect this will be a general bug in how siegfried reads droid-formatted csv files it has created itself (so will impact sf -replay functionality too). I'll try to fix for the next release
