### ISSUE TITLE
Roy inspect FlagSet doesn't include -nopronom resulting in PRONOM IDs being added to identifiers

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#182]
Minor issue, but `-nopronom` isn't part of the inspect flag set which means an identifier will still try and add PRONOM ids to it before returning inspect results. As an optional flag, it can speed up inspection of results if the number of formats in an identifier is high.

**Comment by richardlehane** [comment]
thanks Ross, that'd be great. I'd go with -nopronom for the flag name to keep it symmetrical with the build command
