### ISSUE TITLE
Invalid JSON for fmt/1472

### ISSUE THREAD

**Issue by Sembiance** [richardlehane/siegfried#186]
The file inside the attached [XXX_INT.MSA.zip](https://github.com/richardlehane/siegfried/files/8626256/XXX_INT.MSA.zip) matches against: https://www.nationalarchives.gov.uk/PRONOM/fmt/1472

The PRONOM data has a 'tab' character at the beginning of the MIME field, which causes JSON parsers to choke on siegfried's output.

I don't know how to submit a bug to the PRONOM folks.

**Comment by richardlehane** [comment]
thanks for reporting this Robert, I'll add a test in to guard against invalid JSON values in the mime field

**Comment by Sembiance** [comment]
Awesome, sounds good. PRONOM will also be fixing this in their next release: https://github.com/nationalarchives/pronom/issues/1

Thanks for making siegfried!!

**Comment by richardlehane** [comment]
fixed in v1.9.3
