### ISSUE TITLE
ITForArchivists Google Group?

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#190]
It looks like there's a dead link on [ITForArchivists](https://www.itforarchivists.com/siegfried) to the google group:

![image](https://user-images.githubusercontent.com/1880412/169960893-49f9f444-7fed-4c3c-81fe-47c9f2ea3560.png)

That being said, is there one?

**Comment by richardlehane** [comment]
thanks Ross, seems like an issue with my markdown I'll check it out. There is a group: https://groups.google.com/g/sf-roy but it is pretty dead & I've been neglecting to post recent updates to it (I should)

**Comment by richardlehane** [comment]
I've fixed the link, thanks again
