### ISSUE TITLE
Signatures invalid when trying to update sf via apt (ubuntu/debian)

### ISSUE THREAD

**Issue by hmiguim** [richardlehane/siegfried#197]
Hi, I'm getting this error when trying to update sf after running `apt update`:

```Err:5 https://www.itforarchivists.com buster InRelease
  The following signatures were invalid: EXPKEYSIG A702E58BD13BE0B5 Richard Lehane (siegfried) <richard@itforarchivists.com>
```

**Comment by richardlehane** [comment]
thanks for letting me know Miguel, it looks like my signing key expired over the weekend. I'll aim to fix this tonight

**Comment by richardlehane** [comment]
I've renewed the debian package's signing key and republished it to the ubuntu keyserver.

Re-running this command: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20F802FE798E6857` should now fix it.

Please let me know if any issues!

**Comment by hmiguim** [comment]
Thank you, it is working fine.
