### ISSUE TITLE
sf -update: [FATAL]: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by nunotexbsd** [richardlehane/siegfried#198]
Hello,

`sf -update`
`2022/06/19 14:34:44 [FATAL] failed to update signature file, Get "https://www.itforarchivists.com/siegfried/update": net/http: request canceled while waiting for connection`

Host down it seems.

Thanks,

Nuno Teixeira

**Comment by richardlehane** [comment]
Hi Nuno
I just checked and the website is up. (You can confirm by visiting https://www.itforarchivists.com/siegfried/update in a browser).
Are you behind a proxy? Instructions for running the -update command behind a proxy are described on this issue: https://github.com/richardlehane/siegfried/issues/170
All the best
Richard

**Comment by nunotexbsd** [comment]
Hello,

Its fine now, I can access it and sf -update is ok.

Thanks
