### ISSUE TITLE
Docker image release

### ISSUE THREAD

**Issue by luis100** [richardlehane/siegfried#200]
It would be convinient for us to have a Siegfried available as a Docker container.
To that point, we have done a minimal project that allows to build a Docker image with Siegfried:
https://github.com/keeps/siegfried-docker

And we push this to Docker Hub:
https://hub.docker.com/repository/docker/keeps/siegfried

But this would be better managed by an a GitHub action called by a release dispatch trigger in this repository, just as we do here:
https://github.com/keeps/dbptk-ui/blob/master/.github/workflows/release.yml#L64-L68

We suggest you to incorporate our siegfried-docker project into the [richardlehane](https://github.com/richardlehane) group and set up this inter-project Github workflow, or if you don't mind, call our (keeps) siegfried-docker project from your own Siegfried Github actions release workflow, and we can do the rest.

**Comment by richardlehane** [comment]
Hi Luis - I'm happy to add this to the release.yaml github action. Suggest may be simplest just to keep the repository with you.
Could you do a PR with the changes you need? If necessary to add a secret token to the repository I can do that, perhaps just email it to me?

**Comment by luis100** [comment]
@hmiguim please create PR and send secret via email

**Comment by richardlehane** [comment]
closed with v1.9.5
