### ISSUE TITLE
fmt/1741: signatures with offsets that commence with ranges of wildcards

### ISSUE THREAD

**Issue by richardlehane** [richardlehane/siegfried#203]
Signatures for this new format have min/max offsets 32768/70468 as well as a starting range {0-16}.

The PRONOM parser is incorrectly reading this as a min/max offset of 0/16.

Probably should resolve to min/max offsets of 32768/103252 [not 70484 as confusingly the PRONOM max offset value is relative to the offset value!]

**Comment by Dclipsham** [comment]
Ooh that's subtle. Needs fixing upstream for sure

**Comment by richardlehane** [comment]
sorry I meant *siegfried's* PRONOM parser!! The DROID report for this one looks OK

**Comment by Dclipsham** [comment]
I meant think the sig right now just needs tweaking. Without an anchor before the {0-16} its logically just saying Min offset 32768 max offset 70500 so no reason to combine signature constructs to achieve that I think

**Comment by richardlehane** [comment]
true :)
