### ISSUE TITLE
Auto-update or update in server mode

### ISSUE THREAD

**Issue by luis100** [richardlehane/siegfried#208]
When running Siegfried as a long-standing service, for example as a docker service, it would be important to keep Siegfried up-to-date with the signature database. But, currently, there is no way to call the update action via the service, nor to somehow schedule an auto-update.

This could be done in one of the following ways:
- Add a new action to the Siegfried server API, e.g. `GET /update`, which would call the update action. An external service could be setup to call this endpoint periodically
- Including an auto-update feature into the tool, specifically when it runs in server mode, e.g. `sf -serve localhost:5138 -autoupdate 24h`

**Comment by richardlehane** [comment]
This sounds very doable 👍

**Comment by richardlehane** [comment]
server mode has a new /update route in v1.10.0
