### ISSUE TITLE
Expired key signatures on Debian+

### ISSUE THREAD

**Issue by jaknz** [richardlehane/siegfried#234]
Looks like this happened a year ago too. Good time for a calendar reminder or automated action? 
https://github.com/richardlehane/siegfried/issues/197

`Err:5 https://www.itforarchivists.com buster InRelease
  The following signatures were invalid: EXPKEYSIG A702E58BD13BE0B5 Richard Lehane (siegfried) <richard@itforarchivists.com>`

**Comment by richardlehane** [comment]
apologies! I have just renewed the key and set a calendar reminder.
Please re-open if any issues
