### ISSUE TITLE
Allow siegfried to follow symlinks

### ISSUE THREAD

**Issue by max-moser** [richardlehane/siegfried#245]
Right now, siegfried refuses to scan symbolic links with an error message `file is of type symlink; only regular files can be scanned`:

```bash
mmoser@mx ~ $ ll stderr.log
Permissions Size User   Group  Date Modified Name
lrwxrwxrwx     - mmoser mmoser 27 Feb 13:54  stderr.log -> sf.log

mmoser@mx ~ $ ~/go/bin/sf stderr.log
[FILE] /home/mmoser/stderr.log
[ERROR] file is of type symlink; only regular files can be scanned
---
siegfried   : 1.10.1
scandate    : 2024-02-27T13:55:41+01:00
signature   : default.sig
created     : 2023-12-17T15:38:39+01:00
identifiers : 
  - name    : 'pronom'
    details : 'DROID_SignatureFile_V116.xml; container-signature-20231127.xml'
---
filename : 'stderr.log'
filesize : 6
modified : 2024-02-27T13:54:56+01:00
errors   : 'file is of type symlink; only regular files can be scanned'
matches  :
```

It would be nice to have an option (`-s/-follow-symlinks`?) that makes siegfried follow the symlink to the file to analyze.

**Comment by max-moser** [comment]
For us, the use case is that we have files on disk where the original filename has been "lost" from the FS perspective – they've been renamed to simply `data`, and the original filename is only available from another source.
One way to go about this would be to create an appropriately named symlink to the actual file to analyze.

This can make the difference between correctly identifying a Python file vs. misidentifying it as Plain Text.

**Comment by richardlehane** [comment]
Thanks for this Max. I'm not sure why this symlink block was put in, perhaps to stop recursion into symlinked directories which might cause cycles? 

Should be possible to add it.

A couple of questions:
- would your expectation be this would work only for symlinked files, not symlinked dirs?
- would you expect to see an indication that the file is a symlink in the results e.g. in the warning field? Or does this not matter

**Comment by max-moser** [comment]
I can see the threat of endless cycles with symlinked directories, that could quickly (or rather slowly) spoil somebody's day :sweat_smile: 

Regarding your questions:
* Our use-case is just for files, no directories.
* Speaking purely for us, possibly it would be even better if there were no warning reported, as in our use-case it'd be expected (but that's a _very_ weak preference)

**Comment by max-moser** [comment]
A feasible alternative in our case would actually be to honor the `-name` option when reading a file from disk rather than from stdin – effectively telling siegfried that "the name on disk is wrong, here's the proper one"

**Comment by ross-spencer** [comment]
More on the original rationale and potential to add symlink behavior back in: https://github.com/richardlehane/siegfried/issues/107#issuecomment-334128810

**Comment by richardlehane** [comment]
Hi Max, I've added a new -sym flag that you can use to follow symbolic links to files. To add it to your default configuration do `sf -setconf -sym`. This will be available in next release, out in about a week. I've you'd like to test, there's a release candidate here: https://github.com/richardlehane/siegfried/releases/tag/v1.11.1-rc4

**Comment by max-moser** [comment]
Awesome, thanks a lot!
