### ISSUE TITLE
yml-Outputfile is lacking some of the examined files

### ISSUE THREAD

**Issue by friesey** [richardlehane/siegfried#26]
The Error Message is: 
"panic: runtime error: makeslice: len out of range"
I try to reproduce the error to be more helpfull.
Best, Yvonne

**Comment by richardlehane** [comment]
Hi friesey - I just released sf v0.8.0 and hopefully, fingers crossed, it has fixed your issue (a lot of performance changes including a rewrite of all the IO stuff). But if it hasn't please post an update on this issue and I'll make sure to fix by v0.9

**Comment by friesey** [comment]
Hi, I tried with a PDF that is 321.084 KB big. I lasts some seconds, but works. I cannot try with bigger files just yet, because I do not own any any more. My colleague who deals with the really big files is not available just now.
Thank you for the updated version, I will keep you posted!

**Comment by richardlehane** [comment]
thanks for the update :) I'm glad to hear it got through your breaking file. It would be great if you could try it on even bigger ones (it will be slow - this is hard to avoid for PDFs as must do a full scan to rule out the PDF-A signature). When you're satisfied, please close the issue

**Comment by richardlehane** [comment]
Hi friesey,
I will close this issue for now. But, if you do manage to break siegfried again when testing on big PDFs, please re-open it.
Thanks!
Richard
