### ISSUE TITLE
Crash on network scan

### ISSUE THREAD

**Issue by gleporeNARA** [richardlehane/siegfried#268]
Running:

 sf -sig 64k.sig -multi 100 -coe -csv -log error,slow,progress,stdout z:\1_WorkingStorage\Accessions\* |Tee-Object -FilePath "outputfile.csv"

on a networked server eventually produces the following crash, which halts all progress (but does not exit the program, i.e. only running with errors to stdout ends the program, otherwise it just hangs)

[FILE] z:\1_WorkingStorage\Accessions\0053_2023_xxxx\Records\F223276\CCC 12X4336 GWA TRANSACTIONS FY03 2.PDF
waiting on: 455, potentially excludable: false
waiting on: 479, potentially excludable: false
waiting on: 494, potentially excludable: false
waiting on: 505, potentially excludable: false
waiting on: 1001, potentially excludable: false
waiting on: 1002, potentially excludable: false
waiting on: 1175, potentially excludable: false
waiting on: 1176, potentially excludable: false
waiting on: 1177, potentially excludable: false
waiting on: 1178, potentially excludable: false
waiting on: 1179, potentially excludable: false
waiting on: 1180, potentially excludable: false
waiting on: 1181, potentially excludable: false
waiting on: 1182, potentially excludable: false
waiting on: 1183, potentially excludable: false
waiting on: 1184, potentially excludable: false
waiting on: 1185, potentially excludable: false
waiting on: 1186, potentially excludable: false
waiting on: 1191, potentially excludable: false
waiting on: 1192, potentially excludable: false
waiting on: 1193, potentially excludable: false
waiting on: 1194, potentially excludable: false
waiting on: 1195, potentially excludable: false
waiting on: 1196, potentially excludable: false
waiting on: 1676, potentially excludable: false
waiting on: 1677, potentially excludable: false
Exception 0xc0000006 0x0 0x14f48850000 0x1a6e80
PC=0x1a6e80

runtime.asyncPreempt()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/preempt_amd64.s:8 fp=0xc0057efe60 sp=0xc0057efe58 pc=0x1a6e80
github.com/richardlehane/siegfried/internal/siegreader.(*Reader).ReadByte(0xc004fe4a40?)
        D:/a/siegfried/siegfried/internal/siegreader/reader.go:79 +0x129 fp=0xc0057efe98 sp=0xc0057efe60 pc=0x3e52a9
github.com/richardlehane/match/dwac.(*Dwac).match(0xc000a44080, {0x5a1ba0, 0xc004fe4a40}, 0x5a72f8?, 0xc00082c480?)
        C:/Users/runneradmin/go/pkg/mod/github.com/richardlehane/match@v1.0.5/dwac/dwac.go:142 +0x310 fp=0xc0057effa8 sp=0xc0057efe98 pc=0x3da030
github.com/richardlehane/match/dwac.(*Dwac).Index.func1()
        C:/Users/runneradmin/go/pkg/mod/github.com/richardlehane/match@v1.0.5/dwac/dwac.go:94 +0x36 fp=0xc0057effe0 sp=0xc0057effa8 pc=0x3d9cf6
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0057effe8 sp=0xc0057effe0 pc=0x1a5921
created by github.com/richardlehane/match/dwac.(*Dwac).Index
        C:/Users/runneradmin/go/pkg/mod/github.com/richardlehane/match@v1.0.5/dwac/dwac.go:94 +0xea

goroutine 1 [chan receive]:
runtime.gopark(0xc00006c000?, 0x40?, 0x80?, 0x6f?, 0x60?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000938e30 sp=0xc000938e10 pc=0x1798f6
runtime.chanrecv(0xc006793200, 0xc0009390d8, 0x1)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:583 +0x49d fp=0xc000938ec0 sp=0xc000938e30 pc=0x146b7d
runtime.chanrecv2(0xc0040a50b0?, 0xc0000b2880?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:447 +0x18 fp=0xc000938ee8 sp=0xc000938ec0 pc=0x1466b8
github.com/richardlehane/siegfried.(*Siegfried).IdentifyBuffer(0xc0001366e0, 0x5a2180?, {0x0, 0x0}, {0xc0056acb00, 0x65}, {0x0, 0x0})
        D:/a/siegfried/siegfried/siegfried.go:423 +0xd77 fp=0xc000939148 sp=0xc000938ee8 pc=0x447a97
main.identifyRdr({0x5a2180?, 0xc000380d38?}, 0xc0004dca80, 0xc0008476d8?, 0x546ad0)
        D:/a/siegfried/siegfried/cmd/sf/sf.go:217 +0x16b fp=0xc000939400 sp=0xc000939148 pc=0x4673cb
main.readFile(0xc0004dca80, 0xedaeb6902?, 0xc000052000?)
        D:/a/siegfried/siegfried/cmd/sf/sf.go:194 +0x9d fp=0xc000939490 sp=0xc000939400 pc=0x466ffd
main.identifyFile(0xc0004dca80, 0xc000847680, 0x546ad0)
        D:/a/siegfried/siegfried/cmd/sf/sf.go:203 +0x88 fp=0xc0009394c0 sp=0xc000939490 pc=0x467128
main.identify.func1({0xc0056acb00, 0x65}, {0x5a5f80?, 0xc00447e7e0?}, {0x0, 0x0?})
        D:/a/siegfried/siegfried/cmd/sf/longpath_windows.go:123 +0x67c fp=0xc000939620 sp=0xc0009394c0 pc=0x463a9c
path/filepath.walk({0xc0056acb00, 0x65}, {0x5a5f80, 0xc00447e7e0}, 0xc0009399a8)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/path/filepath/path.go:480 +0x116 fp=0xc0009396e8 sp=0xc000939620 pc=0x2292d6
path/filepath.walk({0xc000951c40, 0x3d}, {0x5a5f80, 0xc004086690}, 0xc0009399a8)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/path/filepath/path.go:504 +0x26f fp=0xc0009397b0 sp=0xc0009396e8 pc=0x22942f
path/filepath.walk({0xc000070e40, 0x35}, {0x5a5f80, 0xc00080c8c0}, 0xc0009399a8)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/path/filepath/path.go:504 +0x26f fp=0xc000939878 sp=0xc0009397b0 pc=0x22942f
path/filepath.walk({0xc000392640, 0x2d}, {0x5a5f80, 0xc00080c850}, 0xc0009399a8)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/path/filepath/path.go:504 +0x26f fp=0xc000939940 sp=0xc000939878 pc=0x22942f
path/filepath.Walk({0xc000392640, 0x2d}, 0xc0009399a8)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/path/filepath/path.go:571 +0x6c fp=0xc000939990 sp=0xc000939940 pc=0x22958c
main.identify(0xc000024240?, {0xc000392640?, 0x0?}, {0x0?, 0x1?}, 0x1?, 0x0?, 0x0?, 0xc000891c80?)
        D:/a/siegfried/siegfried/cmd/sf/longpath_windows.go:126 +0x9c fp=0xc000939a08 sp=0xc000939990 pc=0x46339c
main.main()
        D:/a/siegfried/siegfried/cmd/sf/sf.go:505 +0x1c3d fp=0xc000939f80 sp=0xc000939a08 pc=0x46a4fd
runtime.main()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:250 +0x1f7 fp=0xc000939fe0 sp=0xc000939f80 pc=0x1794d7
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000939fe8 sp=0xc000939fe0 pc=0x1a5921

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000055fb0 sp=0xc000055f90 pc=0x1798f6
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:387
runtime.forcegchelper()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:305 +0xb2 fp=0xc000055fe0 sp=0xc000055fb0 pc=0x179712
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x1a5921
created by runtime.init.6
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000057f80 sp=0xc000057f60 pc=0x1798f6
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgcsweep.go:319 +0xde fp=0xc000057fc8 sp=0xc000057f80 pc=0x163d1e
runtime.gcenable.func1()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:178 +0x26 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x159106
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x1a5921
created by runtime.gcenable
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x2e1cd0b9803c?, 0xf4ba0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000069f70 sp=0xc000069f50 pc=0x1798f6
runtime.goparkunlock(...)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x7e3420)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000069fa0 sp=0xc000069f70 pc=0x161bf3
runtime.bgscavenge(0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000069fc8 sp=0xc000069fa0 pc=0x162205
runtime.gcenable.func2()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:179 +0x26 fp=0xc000069fe0 sp=0xc000069fc8 pc=0x1590a6
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000069fe8 sp=0xc000069fe0 pc=0x1a5921
created by runtime.gcenable
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x179c72?, 0x78c178?, 0x0?, 0x0?, 0xc000059f70?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000059e28 sp=0xc000059e08 pc=0x1798f6
runtime.runfinq()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mfinal.go:193 +0x107 fp=0xc000059fe0 sp=0xc000059e28 pc=0x158167
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x1a5921
created by runtime.createfing
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mfinal.go:163 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc00006bf50 sp=0xc00006bf30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00006bfe0 sp=0xc00006bf50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x2e1ece073ae4?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000065f50 sp=0xc000065f30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000065fe0 sp=0xc000065f50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x2e1ece073ae4?, 0x3?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0004d9f50 sp=0xc0004d9f30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004d9fe0 sp=0xc0004d9f50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004d9fe8 sp=0xc0004d9fe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x2e1ece073ae4?, 0x3?, 0x0?, 0x0?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000067f50 sp=0xc000067f30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000067fe0 sp=0xc000067f50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x2e1ece073ae4?, 0x1?, 0x34?, 0x44?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0004d5f50 sp=0xc0004d5f30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004d5fe0 sp=0xc0004d5f50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004d5fe8 sp=0xc0004d5fe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x838400?, 0x1?, 0x74?, 0xac?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc00008df50 sp=0xc00008df30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008dfe0 sp=0xc00008df50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008dfe8 sp=0xc00008dfe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x2e1ece073ae4?, 0x1?, 0x44?, 0x9b?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0004dbf50 sp=0xc0004dbf30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004dbfe0 sp=0xc0004dbf50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004dbfe8 sp=0xc0004dbfe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x2e1ece073ae4?, 0x1?, 0xd4?, 0x50?, 0x0?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc00008ff50 sp=0xc00008ff30 pc=0x1798f6
runtime.gcBgMarkWorker()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008ffe0 sp=0xc00008ff50 pc=0x15acb1
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x1a5921
created by runtime.gcBgMarkStartWorkers
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/mgc.go:1199 +0x25

goroutine 8 [chan receive]:
runtime.gopark(0xc0003aa000?, 0x0?, 0x20?, 0xbe?, 0x19?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc00008bdc0 sp=0xc00008bda0 pc=0x1798f6
runtime.chanrecv(0xc0008476e0, 0xc00008bf70, 0x1)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:583 +0x49d fp=0xc00008be50 sp=0xc00008bdc0 pc=0x146b7d
runtime.chanrecv1(0x0?, 0x48ab00?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:442 +0x18 fp=0xc00008be78 sp=0xc00008be50 pc=0x146678
main.printer(0xc00008bfa6?, 0xc00039f4f0)
        D:/a/siegfried/siegfried/cmd/sf/sf.go:163 +0x1f0 fp=0xc00008bfc0 sp=0xc00008be78 pc=0x466db0
main.main.func2()
        D:/a/siegfried/siegfried/cmd/sf/sf.go:425 +0x2a fp=0xc00008bfe0 sp=0xc00008bfc0 pc=0x46a96a
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008bfe8 sp=0xc00008bfe0 pc=0x1a5921
created by main.main
        D:/a/siegfried/siegfried/cmd/sf/sf.go:425 +0xa5b

goroutine 301 [chan receive]:
runtime.gopark(0x1?, 0xc0040a0180?, 0xff?, 0xff?, 0xc000935be8?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000935b80 sp=0xc000935b60 pc=0x1798f6
runtime.chanrecv(0xc006793260, 0xc000935db0, 0x1)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:583 +0x49d fp=0xc000935c10 sp=0xc000935b80 pc=0x146b7d
runtime.chanrecv2(0xc000225200?, 0x22?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:447 +0x18 fp=0xc000935c38 sp=0xc000935c10 pc=0x1466b8
github.com/richardlehane/siegfried/internal/bytematcher.(*Matcher).scorer.func6()
        D:/a/siegfried/siegfried/internal/bytematcher/scorer.go:395 +0xf7 fp=0xc000935fe0 sp=0xc000935c38 pc=0x3f2577
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000935fe8 sp=0xc000935fe0 pc=0x1a5921
created by github.com/richardlehane/siegfried/internal/bytematcher.(*Matcher).scorer
        D:/a/siegfried/siegfried/internal/bytematcher/scorer.go:394 +0x425

goroutine 300 [chan receive]:
runtime.gopark(0x0?, 0xc0049da840?, 0xac?, 0x1?, 0xc004905a30?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0049059c8 sp=0xc0049059a8 pc=0x1798f6
runtime.chanrecv(0xc006793380, 0xc004905ca8, 0x1)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:583 +0x49d fp=0xc004905a58 sp=0xc0049059c8 pc=0x146b7d
runtime.chanrecv2(0xc00082cf60?, 0xc000126840?)
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/chan.go:447 +0x18 fp=0xc004905a80 sp=0xc004905a58 pc=0x1466b8
github.com/richardlehane/siegfried/internal/bytematcher.(*Matcher).identify(0xc0001c1ec0, 0xc0063611c0, 0xc0067931a0, 0x5a1ba0?, {0xc0063616e0?, 0x1, 0xc00082c480?})
        D:/a/siegfried/siegfried/internal/bytematcher/identify.go:134 +0x11fa fp=0xc004905f98 sp=0xc004905a80 pc=0x3ef69a
github.com/richardlehane/siegfried/internal/bytematcher.(*Matcher).Identify.func1()
        D:/a/siegfried/siegfried/internal/bytematcher/bytematcher.go:174 +0x3e fp=0xc004905fe0 sp=0xc004905f98 pc=0x3edd1e
runtime.goexit()
        C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc004905fe8 sp=0xc004905fe0 pc=0x1a5921
created by github.com/richardlehane/siegfried/internal/bytematcher.(*Matcher).Identify
        D:/a/siegfried/siegfried/internal/bytematcher/bytematcher.go:174 +0x10f
rax     0x0
rbx     0x0
rcx     0x1000
rdi     0x0
rsi     0x14f48850000
rbp     0xc0057efe88
rsp     0xc0057efe58
r8      0x1000
r9      0x0
r10     0x0
r11     0x601000
r12     0xc0057efe28
r13     0x3e
r14     0xc000053ba0
r15     0x0
rip     0x1a6e80
rflags  0x10204
cs      0x33
fs      0x53
gs      0x2b

**Comment by gleporeNARA** [comment]
Hmm, of course when I recreated the 64k sig the problem went away. I'll close this and see if it happens again.

**Comment by richardlehane** [comment]
thanks Greg, please let me know if recurs! The fact it keeps running if you redirect errors to stdout maybe worth looking into anyway cheers Richard
