### ISSUE TITLE
Runtime error on recursive dir scanning

### ISSUE THREAD

**Issue by paantz** [richardlehane/siegfried#32]
Hardware: iMac (27'', end 2013) / proc: 3,5 GHz Intel Core i7 / memory: 32 Go 1600 MHz DDR3
OS: Os X Yosemite 10.10.2

Siegfried process: recursive directory scanning
Issue: after 1365 file/directory identifications achieved, siegfried stops on runtime error

Herewith screen copy:
-----------------------------------
sf -csv=tr/Volumes/SGRA_ARCHIVES/NEW-Server > /Users/pantz/Documents/APPLICATION-SGRA/analyse-siegfried.csv
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/richardlehane/mscfb.func·001(0x162, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:247 +0x3a1
github.com/richardlehane/mscfb.func·001(0x4d, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x50f, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x166, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:245 +0xf2
github.com/richardlehane/mscfb.func·001(0x2c, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0xa, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x2, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x6f, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x1ca, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x4, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258 +0x33f
github.com/richardlehane/mscfb.func·001(0x0, 0x623ea0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:254 +0x386
github.com/richardlehane/mscfb.(*Reader).traverse(0xc20b903a40, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:262 +0x16e
github.com/richardlehane/mscfb.New(0x131c4f0, 0xc20af71900, 0xc2085ac100, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/mscfb.go:163 +0x2c8
github.com/richardlehane/siegfried/pkg/core/containermatcher.mscfbRdr(0x101d5a0, 0xc2085ac100, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/mscfb.go:30 +0x112
github.com/richardlehane/siegfried/pkg/core/containermatcher.Matcher.Identify(0xc2085007d0, 0x2, 0x2, 0xc20b924480, 0x58, 0x101d5a0, 0xc2085ac100, 0xc2087bf4c8, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/identify.go:43 +0x314
github.com/richardlehane/siegfried/pkg/core/containermatcher.(*Matcher).Identify(0xc208528880, 0xc20b924480, 0x58, 0x101d5a0, 0xc2085ac100, 0xc20b924600, 0x0, 0x0)
	<autogenerated>:10 +0xe1
github.com/richardlehane/siegfried.(*Siegfried).Identify(0xc208010af0, 0xc20b924480, 0x58, 0x1012100, 0xc20b8b6e48, 0x0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/siegfried.go:370 +0x54f
main.identifyFile(0x101d530, 0xc208540440, 0xc208010af0, 0xc20b924480, 0x58, 0x1733000)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:132 +0x2c2
main.func·004(0xc20b924480, 0x58, 0x10120b0, 0xc20828c370, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:119 +0x158
path/filepath.walk(0xc20b924480, 0x58, 0x10120b0, 0xc20828c370, 0xc2087bfd60, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:347 +0x91
path/filepath.walk(0xc209aa8190, 0x4e, 0x10120b0, 0xc209aa8280, 0xc2087bfd60, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:372 +0x51d
path/filepath.walk(0xc20afd4f80, 0x3c, 0x10120b0, 0xc209aa80a0, 0xc2087bfd60, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:372 +0x51d
path/filepath.walk(0xc20a650fc0, 0x31, 0x10120b0, 0xc20a67ac30, 0xc2087bfd60, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:372 +0x51d
path/filepath.walk(0x7fff5fbffc9d, 0x21, 0x10120b0, 0xc20851d270, 0xc2087bfd60, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:372 +0x51d
path/filepath.Walk(0x7fff5fbffc9d, 0x21, 0xc2087bfd60, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/path/filepath/path.go:394 +0xf2
main.multiIdentifyS(0x101d530, 0xc208540440, 0xc208010af0, 0x7fff5fbffc9d, 0x21, 0x0, 0x0, 0x0)
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:122 +0x94
main.main()
	/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:224 +0xd83

**Comment by richardlehane** [comment]
Hi paantz, 
this looks to be an issue with the OLE container library (github.com/richardlehane/mscfb). This library unpacks OLE container files (e.g. old MS Office documents). Seems like the file you are trying it on has an oddly shaped directory tree that breaks the recursive search. I can do a quick fix just to catch this error. If you are comfortable sharing the file causing the crash (you can email it to richard@itforarchivists.com) I will take a closer look and see what is really going on.
Thanks for trying siegfried and for reporting this error!

**Comment by paantz** [comment]
Hi Richard

I run sf in recursive directory scanning and piped the results directly into csv. I have tried the test twice, to see if the problem occurs at same point --> it is the case
below the 'tail -2  analyse-siegfried.csv'
-------------------------------------------
/Volumes/SGRA_ARCHIVES/NEW-Server/01-SGRA-TRANSIT/Transit_FR/01 EN PREPARATION/Senior/Nepal_senior_classementNepal.ai,630670,,pronom,fmt/19,Acrobat PDF 1.5 - Portable Document Format,1.5,application/pdf,byte match at [[[0 8]] [[630663 5]]],extension mismatch
/Volumes/SGRA_ARCHIVES/NEW-Server/01-SGRA-TRANSIT/Transit_FR/01 EN PREPARATION/Senior/Portugal_Senior_classement.ai,643603,,pronom,fmt/19,Acrobat PDF 1.5 - Portable Document Format,1.5,applic
-------------------------------------------
So I took the lest file seen in csv (Portugal.....ai) directly in sf
-------------------------------------------
sf -csv=true /Volumes/SGRA_ARCHIVES/NEW-Server/01-SGRA-TRANSIT/Transit_FR/01\ EN\ PREPARATION/Senior/Portugal_Senior_classement.ai
filename,filesize,errors,identifier,id,format name,format version,mimetype,basis,warning
/Volumes/SGRA_ARCHIVES/NEW-Server/01-SGRA-TRANSIT/Transit_FR/01 EN PREPARATION/Senior/Portugal_Senior_classement.ai,643603,,pronom,fmt/19,Acrobat PDF 1.5 - Portable Document Format,1.5,application/pdf,byte match at [[[0 8]] [[643596 5]]],extension mismatch
-------------------------------------------
It is running fine ..
Finally: yes I can share the file, but I have no idea how I can get his name !

==> If you can give me an indication how to get it, I will send you the faulty file.

Thanks,
Pascal

**Comment by richardlehane** [comment]
Hi Pascal
siegfried's output is buffered before printing so the file causing the crash may be a few files away from the last file in your results (i.e. a small number of additional files were probably scanned but never printed to stdout because of the program crash). You should be able to identify the file by testing a few files immediately (no more than 10 or so!) after your last reported result (in the same or neighbouring directories). Look especially for OLE container files like .doc, .xls, .ppt.

**Comment by paantz** [comment]
Hi Richard,

Finally I got It : a Thumbs.db file
File size is around 23MB : do you have any public FTP server account available were I can download it ?


Le 15 avr. 2015 à 14:23, Richard Lehane <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Pascal
siegfried's output is buffered before printing so the file causing the crash may be a few files away from the last file in your results (i.e. a small number of additional files were probably scanned but never printed to stdout because of the program crash). You should be able to identify the file by testing a few files immediately (no more than 10 or so!) after your last reported result (in the same or neighbouring directories). Look especially for OLE container files like .doc, .xls, .ppt.

**Comment by paantz** [comment]
The associate debug

sf -debug=true Thumbs.db
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x162, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:247<http://github.com/richardlehane/mscfb/directory.go:247> +0x3a1
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x4d, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x50f, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x166, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:245<http://github.com/richardlehane/mscfb/directory.go:245> +0xf2
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x2c, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0xa, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x2, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x6f, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x1ca, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x4, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:258<http://github.com/richardlehane/mscfb/directory.go:258> +0x33f
github.com/richardlehane/mscfb.func·001<http://github.com/richardlehane/mscfb.func·001>(0x0, 0x623ea0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:254<http://github.com/richardlehane/mscfb/directory.go:254> +0x386
github.com/richardlehane/mscfb<http://github.com/richardlehane/mscfb>.(*Reader).traverse(0xc208513b20, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/directory.go:262<http://github.com/richardlehane/mscfb/directory.go:262> +0x16e
github.com/richardlehane/mscfb.New<http://github.com/richardlehane/mscfb.New>(0x101d828, 0xc208481d00, 0x6236c0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/mscfb/mscfb.go:163<http://github.com/richardlehane/mscfb/mscfb.go:163> +0x2c8
github.com/richardlehane/siegfried/pkg/core/containermatcher.mscfbRdr<http://github.com/richardlehane/siegfried/pkg/core/containermatcher.mscfbRdr>(0x101d750, 0xc2085ac100, 0x0, 0x0, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/mscfb.go:30<http://github.com/richardlehane/siegfried/pkg/core/containermatcher/mscfb.go:30> +0x112
github.com/richardlehane/siegfried/pkg/core/containermatcher.Matcher.Identify<http://github.com/richardlehane/siegfried/pkg/core/containermatcher.Matcher.Identify>(0xc2084fe7d0, 0x2, 0x2, 0x7fff5fbffcc7, 0x9, 0x101d750, 0xc2085ac100, 0xc208595bf8, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/identify.go:43<http://github.com/richardlehane/siegfried/pkg/core/containermatcher/identify.go:43> +0x314
github.com/richardlehane/siegfried/pkg/core/containermatcher<http://github.com/richardlehane/siegfried/pkg/core/containermatcher>.(*Matcher).Identify(0xc208524880, 0x7fff5fbffcc7, 0x9, 0x101d750, 0xc2085ac100, 0xc2084c06c0, 0x0, 0x0)
<autogenerated>:10 +0xe1
github.com/richardlehane/siegfried<http://github.com/richardlehane/siegfried>.(*Siegfried).Identify(0xc208010af0, 0x7fff5fbffcc7, 0x9, 0x10121d0, 0xc20802e6b0, 0x13e63, 0x0, 0x0)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/siegfried.go:370<http://github.com/richardlehane/siegfried/siegfried.go:370> +0x54f
main.identifyFile(0x101d718, 0x623ea0, 0xc208010af0, 0x7fff5fbffcc7, 0x9, 0x1733000)
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:132<http://github.com/richardlehane/siegfried/cmd/sf/sf.go:132> +0x2c2
main.main()
/private/tmp/siegfried20150415-4862-btufud/siegfried-1.0.0/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:231<http://github.com/richardlehane/siegfried/cmd/sf/sf.go:231> +0xcec
Le 15 avr. 2015 à 14:49, Pascal ANTZ <Pascal.ANTZ@afp.com<mailto:Pascal.ANTZ@afp.com>> a écrit :

Hi Richard,

Finally I got It : a Thumbs.db file
File size is around 23MB : do you have any public FTP server account available were I can download it ?


Le 15 avr. 2015 à 14:23, Richard Lehane <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Pascal
siegfried's output is buffered before printing so the file causing the crash may be a few files away from the last file in your results (i.e. a small number of additional files were probably scanned but never printed to stdout because of the program crash). You should be able to identify the file by testing a few files immediately (no more than 10 or so!) after your last reported result (in the same or neighbouring directories). Look especially for OLE container files like .doc, .xls, .ppt.

**Comment by richardlehane** [comment]
Hi Pascal
yep that makes sense - Thumbs.db are OLE files. Would be great to look at it. I've no ftp but can share a dropbox folder with you that you could upload it to if you have a dropbox account? If so, just mail me your contact.
thanks very much for digging into this, is a big help,
Richard

**Comment by paantz** [comment]
Hi Richard,
I sent you my personal email, private.

**Comment by richardlehane** [comment]
Hi Pascal
I've made a change to the mscfb library which should prevent the panic. It will mean that your Thumbs.db won't get properly unpacked, so may affect identification of that file (there is a container signature for Thumbs.db that won't be applied to this file), but it should also mean that sf handles the error gracefully (you should get an error report for that file) and completes the rest of the identifications.

For some reason, your email sending your address hasn't come through? But I did find an address for you on your linkedin profile and have tried sharing a dropbox folder with that email. I'm definitely still keen to take a look at that file - may be able to make further changes to my mscfb if it is a legal construction that I'm not handling properly.

I expect to put a version 1.1 release of siegfried out shortly (after the next PRONOM update which I believe is scheduled for this month) & this release will contain your bugfix. 

thanks again
Richard

**Comment by paantz** [comment]
Hi Richard

I found your folder and just dowloaded a zip file on it.

thanks
Pascal

Le 18 avr. 2015 à 03:54, Richard Lehane <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Pascal
I've made a change to the mscfb library which should prevent the panic. It will mean that your Thumbs.db won't get properly unpacked, so may affect identification of that file (there is a container signature for Thumbs.db that won't be applied to this file), but it should also mean that sf handles the error gracefully (you should get an error report for that file) and completes the rest of the identifications.

For some reason, your email sending your address hasn't come through? But I did find an address for you on your linkedin profile and have tried sharing a dropbox folder with that email. I'm definitely still keen to take a look at that file - may be able to make further changes to my mscfb if it is a legal construction that I'm not handling properly.

I expect to put a version 1.1 release of siegfried out shortly (after the next PRONOM update which I believe is scheduled for this month) & this release will contain your bugfix.

thanks again
Richard

**Comment by richardlehane** [comment]
Thanks Pascal: I've just had a look at the file & have patched mscfb so it exits with an error rather than panics. This should prevent sf from breaking in future (you will see the error message in the results but it will continue scanning as normal).

It does appear that the directory structure within that Thumbs.db file is malformed. It seems to have duplicate entries in the left/right/child relationships between directory structures.

Thanks very much for reporting this issue. You should see the fix in v1.1 (out soon!)

**Comment by richardlehane** [comment]
Hi Pascal
Just an update on that siegfried issue you reported. Version 1.1 is now released for windows (mac and linux will hopefully follow soon) and has your fix.
Thanks again for reporting the bug
Richard
