### ISSUE TITLE
Inconsistent encoding in YAML output for legacy 8 bit encoded file names

### ISSUE THREAD

**Issue by despens** [richardlehane/siegfried#42]
Siegfried represents the file names as-is in the YAML it produces. This can lead to mixed encodings within one YAML stream.

Probably is should be considered a problem of the scanned file system if it contains multiple encodings for the names, however when Siegfried looks into legacy ZIP archives, 8 bit encoded file names can be very common. Since they are not part of the scanned file system, it would seem like bad practice to fix the names inside such a container.

I am not sure what solutions might exist, since AFAIK file names in ZIP archives outside of ASCII can be whatever and the encoding is not recorded.

However, the mixed encodings renders some of the YAML output invalid, which in some cases makes it unusable in certain environments.

**Comment by richardlehane** [comment]
This is an interesting one!
This may be something a bit lower down in the go stack? From the golang archive/zip library I just get a UTF8 string for a file name (same as for regular file system names) so I never really have to deal with string encodings. At the moment I take that and just do a very simple sanitisation for YAML that simply adds a quote to any single quotes (') already in the string: with the idea that the full string will then be quoted and then safe to print. I can beef up that sanitisation method but I'm a little unsure where to start: can you share an example or two of some of the broken YAML you're getting?

**Comment by despens** [comment]
Will send you a case via email.

**Comment by richardlehane** [comment]
OK, I've had a look at this and it looks pretty ugly :(

My comment above was wrong: I don't get a UTF8 string from the archive/zip library, I just get a string containing arbitrary bytes. This exposes an underlying problem with ZIP itself - file names can have any encoding and they aren't declared: [https://marcosc.com/2008/12/zip-files-and-encoding-i-hate-you/](https://marcosc.com/2008/12/zip-files-and-encoding-i-hate-you/)
Keep this issue open. I think I can hack around by:
1. checking whether ZIP file names are valid [UTF8](https://golang.org/pkg/unicode/utf8/#ValidString)
2. if not... [determine encoding](https://godoc.org/golang.org/x/net/html/charset#DetermineEncoding) & then [decode as UTF8](https://godoc.org/golang.org/x/text/encoding)

I'd like to do a little research to make sure this is the best of the bad options for this, so may not have this fixed soon, but will add it to the list for the 1.2 release.

A temporary solution when you hit this problem may be to unzip the problematic zips before scanning. So long as you unzip on the same OS the files you zipped with, you should get correct file names which `sf` will then handle normally.
