### ISSUE TITLE
32 bit Ubuntu download missing

### ISSUE THREAD

**Issue by glepore70** [richardlehane/siegfried#44]
There doesn't appear to be any files available for download at:
http://dl.bintray.com/siegfried/debian/dists/wheezy/main/binary-i386/
for 32 bit Ubuntu.

**Comment by richardlehane** [comment]
Hi @glepore70
I'm very sorry but there isn't a deb install available for 32-bit linux. I've updated the install instructions to make this clear. 
Siegfried will work on 32-bit but you'll need to install from source. Instructions to do this are here: https://github.com/richardlehane/siegfried/wiki/Getting-started (go to "Install from source"). Please let me know if you have any trouble following these instructions... if you can't get it to work, I'll build a 32-bit binary for you and pop it onto the Github releases.
cheers
Richard
