### ISSUE TITLE
panic on osx 10.8

### ISSUE THREAD

**Issue by atomotic** [richardlehane/siegfried#45]
fresh install on osx 10.8, using `go get`:

	➜  ~  go version
	go version go1.4.2 darwin/amd64

	➜  ~  go env
	GOARCH="amd64"
	GOBIN=""
	GOCHAR="6"
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOOS="darwin"
	GOPATH="/Users/raffaele/go"
	GORACE=""
	GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
	GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
	CC="clang"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
	CXX="clang++"
	CGO_ENABLED="1"

	➜  ~  sf -update
	panic: runtime error: slice bounds out of range

	goroutine 1 [running]:
	github.com/richardlehane/siegfried/pkg/core/persist.(*LoadSaver).get(0xc20803cc90, 0xffffffffffffff00, 0x0, 0x0, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/persist/persist.go:54 +0x1f1
	github.com/richardlehane/siegfried/pkg/core/persist.(*LoadSaver).getCollection(0xc20803cc90, 0x0, 0x0, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/persist/persist.go:194 +0x82
	github.com/richardlehane/siegfried/pkg/core/persist.(*LoadSaver).LoadInts(0xc20803cc90, 0x0, 0x0, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/persist/persist.go:322 +0x43
	github.com/richardlehane/siegfried/pkg/core/priority.Load(0xc20803cc90, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/priority/priority.go:232 +0x2e3
	github.com/richardlehane/siegfried/pkg/core/bytematcher.Load(0xc20803cc90, 0xc2082e1550)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/bytematcher/bytematcher.go:75 +0x168
	github.com/richardlehane/siegfried/pkg/core/containermatcher.loadCTests(0xc20803cc90, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/container.go:257 +0x10f
	github.com/richardlehane/siegfried/pkg/core/containermatcher.loadCM(0xc20803cc90, 0x2)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/container.go:144 +0x78
	github.com/richardlehane/siegfried/pkg/core/containermatcher.Load(0xc20803cc90, 0x0, 0x0, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/container.go:42 +0xb5
	github.com/richardlehane/siegfried.Load(0xc20800a520, 0x20, 0x0, 0x0, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/siegfried.go:179 +0x868
	main.updateSigs(0x0, 0x0, 0x0, 0x0)
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/cmd/sf/update.go:53 +0x2db
	main.main()
		/Users/raffaele/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:217 +0x341

	goroutine 17 [syscall, locked to thread]:
	runtime.goexit()
		/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

	goroutine 7 [IO wait]:
	net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
	net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
	net.(*netFD).Read(0xc2080101c0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x1012230, 0xc20802ab98)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
	net.(*conn).Read(0xc20803e058, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
	net/http.noteEOFReader.Read(0x10139c0, 0xc20803e058, 0xc208094108, 0xc20800f000, 0x1000, 0x1000, 0x353b40, 0x0, 0x0)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1270 +0x6eraffaele/go
	net/http.(*noteEOFReader).Read(0xc20800a620, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
		<autogenerated>:125 +0xd4
	bufio.(*Reader).fill(0xc20805c4e0)
		/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
	bufio.(*Reader).Peek(0xc20805c4e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
		/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:132 +0xf0
	net/http.(*persistConn).readLoop(0xc2080940b0)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:842 +0xa4
	created by net/http.(*Transport).dialConn
		/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

	goroutine 8 [select]:
	net/http.(*persistConn).writeLoop(0xc2080940b0)
		/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
	created by net/http.(*Transport).dialConn
		/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc

**Comment by atomotic** [comment]
tried also compiling with gcc, same behaviour
`export CXX=g++-4.9`

**Comment by richardlehane** [comment]
Hi Raffaelle
can you run sf -version and double check you have 1.2.0? I changed the signature file format in the update to 1.2.0 and sf 1.1 won't load the latest signature file. The error you are getting looks very much like this scenario.

If `go get` didn't pull down the latest version of sf, you can force it to by deleting contents of your $GOPATH\src\github.com\richardlehane as well as 
$GOPATH\pkg\[ARCH]\github.com\richardlehane.
Using the `-a` flag with go get might work as well i.e. `go get -a github.com/richardlehane/siegfried/cmd/sf`

**Comment by atomotic** [comment]
the installed version is 1.2.0, i installed after removing everything from $GOPATH.
i've removed now `~/siegfried/pronom.sig` and `~/.siegfried/pronom.gob` (deprecated, right?), and now works.

thanks!
