### ISSUE TITLE
error reading signature file

### ISSUE THREAD

**Issue by workflowsguy** [richardlehane/siegfried#49]
I have installed Siegfried on OS X via homebrew.

When executing `sf FILE.EXT` I get the error

Error: error loading signature file, got: Siegfried: error reading signature file; got gob: unknown type id or corrupted data
Try running `sf -update`

I can run "sf -update" as often as I want, but the error message persists.

Update: `mistydemeo/digipres/siegfried`has version 1.0, which does not seem to be the most recent version. Could you please update the tap?

**Comment by richardlehane** [comment]
Hi workflowsguy
thanks for reporting this & for trying sf.

The signature format changed with sf versions 1.1 and 1.2. Attempts to use the newer signatures with an older install of sf should fail gracefully, not break like this, & I will endeavour to make future upgrades less error prone.

The immediate solution for you is either to upgrade to the latest version of sf (1.2.2) or to rebuild your 1.0 signatures.

You can rebuild your 1.0 signatures with the command:

    roy build

You may need to prefix this with `sudo` depending on where your home directory is. So try `sudo roy build` if you get a permissions error.

Re. upgrading to 1.2.2:

I don't host the brew tap myself but will see if I can fork and push an update, perhaps this coming weekend. 

Your other option for upgrading is to build sf from source. Instructions for this are here: [https://github.com/richardlehane/siegfried/wiki/Getting-started#installing-from-source](https://github.com/richardlehane/siegfried/wiki/Getting-started#installing-from-source). If you'd like to try this, I'm happy to walk you through any issues you have - just add further comments to this issue.

All the best
Richard

**Comment by workflowsguy** [comment]
Thank you for the information, Richard.

I have successfully rebuilt the signatures with `roy` and can get going. In the long run, having a current version of Siegfried installable through Homebrew would be great, though.

Cheers,
Stefan

**Comment by richardlehane** [comment]
Hi Stefan
the Homebrew tap has now been updated to 1.2.2
all the best
Richard
