### ISSUE TITLE
EXT data appearing for Folders with . values in -DROID output

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#51]
Discovered looking at the differences between SF DROID and DROID DROID in the droidsqliteanalysistool. 

E.g. This folder in my version of the OPF format corpus: https://github.com/ross-spencer/opf-format-corpus/tree/master/format-corpus/variations/variations/application/x-iwork-pages-sffpages/09-4.1-923

**Comment by richardlehane** [comment]
oh weird! thx for spotting
