### ISSUE TITLE
PRONOM sig version information

### ISSUE THREAD

**Issue by asciim0** [richardlehane/siegfried#54]
This might be available somewhere and I just can't find it - but is it possible to see information about the PRONOM sig file currently used? sf -version shows the Siegfried version information and the pronom.sig file is named just that without a version# in it. If it's not available somewhere already, this would be a nice feature to have.

**Comment by richardlehane** [comment]
Hi Michelle
Each time you run sf you should see detailed information about the PRONOM signature file being used, including any modifications made, in the provenance block at the start of the results: https://github.com/richardlehane/siegfried/wiki/Identifying-file-formats#interpreting-the-output (see the "Details" field under the "Identifiers" section).
But I agree, seeing details about the default signature file when you run sf -version would be handy and a good feature to add.
I should be able to get something in for the next release (1.3) that I hope to have finished in the next week or so. 
Thanks very much for trying siegfried and for reporting this issue,
Richard

**Comment by richardlehane** [comment]
Hi Michelle
From the next sf release (likely sometime next week or the week after), the -version command will print:
![capture](https://cloud.githubusercontent.com/assets/157422/9975187/d8d1ebce-5ef5-11e5-9437-9635b8783513.png)

Hope this is what you had in mind.
cheers
Richard

**Comment by asciim0** [comment]
Perfect! Thanks a lot!
