### ISSUE TITLE
Mechanism to throttle scanning in Siegfried?

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#61]
We're coming a cropper with bandwidth issues on our SAN. It's not a showstopper by observing behavior with both DROID and Siegfried I can east the situation by throttling DROID, I don't know if that's possible in SF,

Depending on whether there was a precedent for this type of behavior in a CLI tool like this, I can probably wrap SF in a bash or batch script to achieve the same result.

**Comment by richardlehane** [comment]
Hi Ross
added a -throttle flag to sf. It takes a duration e.g. sf -throttle 50ms DIR or sf -throttle 1s DIR

**Comment by ross-spencer** [comment]
It worked a treat. Thanks Richard.
