### ISSUE TITLE
If another module panics, have SF report no ID and continue scanning

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#62]
(Sorry!) Me again! 

I've an OLE2 object that I need to debug, and maybe also need to find a mechanism of sharing with you. That will help to iron out a panic in the MSCFB module (I believe).

The undesirable behavior from Siegfried's perspective is Go panicing and exiting as follows:

      panic: runtime error: index out of range

      goroutine 1 [running]:
      github.com/richardlehane/mscfb.(*Reader).setMiniStream(0x14286d40, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/streams.go:26 +0x346
      github.com/richardlehane/mscfb.New(0x33190118, 0x1468b650, 0x40, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/mscfb.go:160 +0x1d4
      github.com/richardlehane/siegfried/pkg/core/containermatcher.mscfbRdr(0xd29520, 0x143ca500, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/mscfb.go:30 +0xb6
      github.com/richardlehane/siegfried/pkg/core/containermatcher.Matcher.Identify(0x128a24e0, 0x2, 0x2, 0x14740780, 0x5d, 0xd29520, 0x143ca500, 0x128e33fc, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/identify.go:37 +0x159
      github.com/richardlehane/siegfried/pkg/core/containermatcher.(*Matcher).Identify(0x12d322d0, 0x14740780, 0x5d, 0xd29520, 0x143ca500, 0x14286c00, 0x0, 0x0)
              <autogenerated>:11 +0xb4
      github.com/richardlehane/siegfried.(*Siegfried).Identify(0x12d16050, 0xd245c0, 0x1514d5b0, 0x14740780, 0x5d, 0x0, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/siegfried.go:310 +0x91d
      main.identifyRdr(0x32f201c8, 0x12d136c0, 0x12d16050, 0xd245c0, 0x1514d5b0, 0x2800, 0x0, 0x14740780, 0x5d, 0x0, ...)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:193 +0x98
      main.identifyFile(0x32f201c8, 0x12d136c0, 0x12d16050, 0x14740780, 0x5d, 0x2800, 0x0, 0x159b3ee0, 0x19)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:187 +0x14d
      main.multiIdentifyS.func1(0x14740780, 0x5d, 0xd24590, 0x1500aa50, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:172 +0x544
      path/filepath.walk(0x14740780, 0x5d, 0xd24590, 0x1500aa50, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:349 +0x70
      path/filepath.walk(0x14740360, 0x52, 0xd24590, 0x1500a8c0, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.walk(0x1470a5f0, 0x45, 0xd24590, 0x1470a640, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.walk(0x1445e9c0, 0x31, 0xd24590, 0x1463c690, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.walk(0x13eb4840, 0x27, 0xd24590, 0x152de320, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.walk(0x13eb4600, 0x22, 0xd24590, 0x152de0f0, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.walk(0x15704420, 0x1d, 0xd24590, 0x15403630, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.walk(0x12885960, 0x10, 0xd24590, 0x12d160f0, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9
      path/filepath.Walk(0x12885960, 0x10, 0x128e3c14, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:396 +0xb7
      main.multiIdentifyS(0x32f201c8, 0x12d136c0, 0x12d16050, 0x12885960, 0x10, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:175 +0xa2
      main.main()
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:391 +0x20db

While it is important to log that the tool couldn't handle the file as expected, if it can report an error or no-id, and move on, then continue to scan the rest of the collection, then we still have a useful data set containing a complete overview of a collection that we can work from.

**Comment by ross-spencer** [comment]
N.B. I rebuilt the MCSFB module after doing a new pull request, and then rebuilt the develop branch of SF, the panic over the specific file is still there, the error looks slightly different: 

      panic: runtime error: index out of range

      goroutine 1 [running]:
      github.com/richardlehane/mscfb.(*Reader).setMiniStream(0x12bba140, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/streams.go:26 +0x346
      github.com/richardlehane/mscfb.New(0x330c0068, 0x12bbe060, 0x99c4e0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/mscfb.go:160 +0x1d4
      github.com/richardlehane/siegfried/pkg/core/containermatcher.mscfbRdr(0x330c0000, 0x12bce000, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/mscfb.go:30 +0xb6
      github.com/richardlehane/siegfried/pkg/core/containermatcher.Matcher.Identify(0x127324e0, 0x2, 0x2, 0x127182d0, 0x2a, 0x330c0000, 0x12bce000, 0x127719e4, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/identify.go:37 +0x159
      github.com/richardlehane/siegfried/pkg/core/containermatcher.(*Matcher).Identify(0x12bb4df0, 0x127182d0, 0x2a, 0x330c0000, 0x12bce000, 0x12bba0c0, 0x0, 0x0)
              <autogenerated>:11 +0xb4
      github.com/richardlehane/siegfried.(*Siegfried).Identify(0x12717860, 0x3c45c0, 0x12bb8000, 0x127182d0, 0x2a, 0x0, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/siegfried.go:310 +0x91d
      main.identifyRdr(0x3c8c90, 0x12ba61e0, 0x12717860, 0x3c45c0, 0x12bb8000, 0x2800, 0x0, 0x127182d0, 0x2a, 0x0, ...)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:193 +0x98
      main.identifyFile(0x3c8c90, 0x12ba61e0, 0x12717860, 0x127182d0, 0x2a, 0x2800, 0x0, 0x12ba6220, 0x19)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:187 +0x14d
      main.main()
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:400 +0x1ecf

**Comment by richardlehane** [comment]
& just when I'd merged 1.4.2!

Yep - this is an mscfb bug: there shouldn't be any panics at all from mscfb (a task on my to do list is to use https://github.com/dvyukov/go-fuzz to eliminate these). I'll try to track this down but if you can share the offending file will be a help.

**Comment by richardlehane** [comment]
have applied a quick fix to mscfb https://github.com/richardlehane/mscfb/commit/67b38e8979f84d14fafe791c2187044394a5d90b

re. the general point - yep, sf definitely shouldn't crash like this! Rather than recovering from panics, I'd prefer to harden the underlying libraries and report errors in an orderly fashion, to avoid panics altogether. A lot of mscfb errors are being caught now but fuzzing should uncover any remaining possible bugs. Looking over the mscfb code would be great also to start reporting more useful errors (e.g. suspect this bug in your OLE is a negative or 0 value numMiniFatSector in the header but with a valid miniFatSectorLoc).

**Comment by ross-spencer** [comment]
Cool. The fix enables SF to push on. I see "Not a valid OLE2 file" I suspect you're right about the structure of this particular OLE2 file. I'll be away from the office for a week so when I'm back I'll work out the necessary disclaimer around the record to be able to share it. 

Thanks for the short-term fix. It should help me to produce a working report.

**Comment by richardlehane** [comment]
I had another look at the spec: I *may* have been a little too heavy handed erroring here (just re-read the spec and something I was treating as a *must* is only a *can* in fact!). Pushed another commit that treats a zero value in this field as being an mscfb file without a mini FAT - this may allow your file to be read.

**Comment by richardlehane** [comment]
Have fuzzed mscfb: this process generated one "crasher" (potential file that can cause a panic)... have fixed that panic and improved mscfb error reporting (specific error types for all different failure modes + additional info such as bad offsets). Don't expect mscfb to cause many crashes in future! (But please reopen if it does)
