### ISSUE TITLE
Build error in latest Master branch?

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#64]
I've updated all external packages before building, msoleps, mscfb, etc. 
    
    C:\Source\git\go\src\github.com\richardlehane\siegfried\cmd\sf>go install
    # github.com/richardlehane/siegfried/pkg/core/siegreader
    ..\..\pkg\core\siegreader\siegreader.go:93: cannot use buf (type []byte) as type io.Reader in argument to characterize.Detect:
        []byte does not implement io.Reader (missing Read method)

**Comment by ross-spencer** [comment]
Version 4.1.3. builds okay for me if I checkout that tag.

**Comment by richardlehane** [comment]
Hi Ross
I changed the API for the https://github.com/richardlehane/characterize package with the latest release, this is causing your build error and you'll need to update it as well (it will be building with an older version of the package).

If you're building with `go get` you can use the `-u` flag to force update of dependencies. Another fix would just be to delete the characterize package from your /src and /pkg folders before doing the install.

**Comment by ross-spencer** [comment]
Cool! That worked. Thanks Richard!

**Comment by richardlehane** [comment]
no problemo
