### ISSUE TITLE
fatal error: runtime: cannot map pages in arena address space

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#68]
Command used: 
   
    sf -droid -log p,e,t "Z:\Master Copies" > sf-masters-22-jan-nohash.csv

Error:

      [FILE] Z:\Master Copies\[redacted]\[redacted]\[redacted]\[redacted].doc
      fatal error: runtime: cannot map pages in arena address space

      runtime stack:
      runtime.throw(0x813b60, 0x30)
              c:/go/src/runtime/panic.go:527 +0x7f
      runtime.sysMap(0x0, 0x100000, 0x32a0fd01, 0x9a3e18)
              c:/go/src/runtime/mem_windows.go:112 +0x78
      runtime.mHeap_SysAlloc(0x991d40, 0x100000, 0x0)
              c:/go/src/runtime/malloc.go:423 +0x121
      runtime.mHeap_Grow(0x991d40, 0x8, 0x0)
              c:/go/src/runtime/mheap.go:628 +0x52
      runtime.mHeap_AllocSpanLocked(0x991d40, 0x1, 0x644d9298)
              c:/go/src/runtime/mheap.go:532 +0x574
      runtime.mHeap_Alloc_m(0x991d40, 0x1, 0x9, 0x0, 0x644d9298)
              c:/go/src/runtime/mheap.go:425 +0x281
      runtime.mHeap_Alloc.func1()
              c:/go/src/runtime/mheap.go:484 +0x3d
      runtime.systemstack(0x32a0feb4)
              c:/go/src/runtime/asm_386.s:283 +0x81
      runtime.mHeap_Alloc(0x991d40, 0x1, 0x9, 0x27f0100, 0x14ce)
              c:/go/src/runtime/mheap.go:485 +0x5a
      runtime.mCentral_Grow(0x996b90, 0x0)
              c:/go/src/runtime/mcentral.go:190 +0x8e
      runtime.mCentral_CacheSpan(0x996b90, 0x644d9298)
              c:/go/src/runtime/mcentral.go:86 +0x439
      runtime.mCache_Refill(0x260254, 0x9, 0x644d9298)
              c:/go/src/runtime/mcache.go:118 +0xae
      runtime.mallocgc.func2()
              c:/go/src/runtime/malloc.go:611 +0x2b
      runtime.systemstack(0x125f4a00)
              c:/go/src/runtime/asm_386.s:267 +0x57
      runtime.mstart()
              c:/go/src/runtime/proc1.go:674

      goroutine 1 [running]:
      runtime.systemstack_switch()
              c:/go/src/runtime/asm_386.s:222 fp=0x15e99174 sp=0x15e99170
      runtime.mallocgc(0x80, 0x785f40, 0x1, 0x4d202c6e)
              c:/go/src/runtime/malloc.go:612 +0x65a fp=0x15e991dc sp=0x15e99174
      runtime.newobject(0x785f40, 0x333180f8)
              c:/go/src/runtime/malloc.go:760 +0x41 fp=0x15e991f0 sp=0x15e991dc
      github.com/richardlehane/mscfb.makeDirEntry(0x33318100, 0x100, 0x5e300, 0x6427df80)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/file.go:61 +0x2f fp=0x15e99314 sp=0x15e991f0
      github.com/richardlehane/mscfb.(*Reader).setDirEntries(0x1450cc40, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/file.go:95 +0x2c5 fp=0x15e993ac sp=0x15e99314
      github.com/richardlehane/mscfb.New(0x3a0e90, 0x15798a80, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/mscfb/mscfb.go:300 +0x19f fp=0x15e99404 sp=0x15e993ac
      github.com/richardlehane/siegfried/pkg/core/containermatcher.mscfbRdr(0x15796b40, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/mscfb.go:30 +0xa7 fp=0x15e9943c sp=0x15e99404
      github.com/richardlehane/siegfried/pkg/core/containermatcher.Matcher.Identify(0x126024b0, 0x2, 0x2, 0x14c7c000, 0x95, 0x15796b40, 0x15e995e0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/pkg/core/containermatcher/identify.go:37 +0x15e fp=0x15e994b0 sp=0x15e9943c
      github.com/richardlehane/siegfried/pkg/core/containermatcher.(*Matcher).Identify(0x12abac90, 0x14c7c000, 0x95, 0x15796b40, 0x14b18c01, 0x0, 0x0)
              <autogenerated>:11 +0xac fp=0x15e994d8 sp=0x15e994b0
      github.com/richardlehane/siegfried.(*Siegfried).Identify(0x125e7950, 0x394598, 0x14b18b30, 0x14c7c000, 0x95, 0x0, 0x0, 0x43a051, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/siegfried.go:310 +0x900 fp=0x15e99654 sp=0x15e994d8
      main.identifyRdr(0x32f70100, 0x12a98ce0, 0x125e7950, 0x394598, 0x14b18b30, 0x76400, 0x0, 0x14c7c000, 0x95, 0x0, ...)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:189 +0x98 fp=0x15e997b8 sp=0x15e99654
      main.identifyFile(0x32f70100, 0x12a98ce0, 0x125e7950, 0x14c7c000, 0x95, 0x76400, 0x0, 0x15798a40, 0x19)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:183 +0x190 fp=0x15e99808 sp=0x15e997b8
      main.multiIdentifyS.func1(0x14c7c000, 0x95, 0x394568, 0x14e55400, 0x0, 0x0, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:168 +0x5d4 fp=0x15e998bc sp=0x15e99808
      path/filepath.walk(0x14c7c000, 0x95, 0x394568, 0x14e55400, 0x15e99c10, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:349 +0x70 fp=0x15e99958 sp=0x15e998bc
      path/filepath.walk(0x1565b100, 0x7e, 0x394568, 0x15030eb0, 0x15e99c10, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9 fp=0x15e999f4 sp=0x15e99958
      path/filepath.walk(0x1503fef0, 0x42, 0x394568, 0x1503ff40, 0x15e99c10, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9 fp=0x15e99a90 sp=0x15e999f4
      path/filepath.walk(0x14dbc000, 0x2e, 0x394568, 0x1503fd10, 0x15e99c10, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9 fp=0x15e99b2c sp=0x15e99a90
      path/filepath.walk(0x125e5980, 0x10, 0x394568, 0x125e62d0, 0x15e99c10, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:374 +0x3f9 fp=0x15e99bc8 sp=0x15e99b2c
      path/filepath.Walk(0x125e5980, 0x10, 0x15e99c10, 0x0, 0x0)
              c:/go/src/path/filepath/path.go:396 +0xb7 fp=0x15e99bfc sp=0x15e99bc8
      main.multiIdentifyS(0x32f70100, 0x12a98ce0, 0x125e7950, 0x125e5980, 0x10, 0x0, 0x0, 0x1000, 0x0, 0x0)
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:171 +0x84 fp=0x15e99c38 sp=0x15e99bfc
      main.main()
              C:/Source/git/go/src/github.com/richardlehane/siegfried/cmd/sf/sf.go:388 +0x210f fp=0x15e99fa8 sp=0x15e99c38
      runtime.main()
              c:/go/src/runtime/proc.go:111 +0x234 fp=0x15e99fd0 sp=0x15e99fa8
      runtime.goexit()
              c:/go/src/runtime/asm_386.s:1662 +0x1 fp=0x15e99fd4 sp=0x15e99fd0

I don't understand why without MD5 we get past the issues in https://github.com/richardlehane/siegfried/issues/66 

But we're reaching further down in the directory walk here... It goes beyond the issues with the folders there by approximately 7000 more files/dirs before this (MSCFB)? error. The difference is no MD5.

**Comment by richardlehane** [comment]
Hi Ross
Does this one reproduce if you just run against this particular file? The error is happening with the memory mapping: it may be caused by an illegal access from the mscfb package but may also just be an IO issue.

Re. MD5: the reason you get further without MD5 is you need to do full file reads for every file when you are doing hashing. SF itself doesn't necessarily need to do full file reads (it uses special sauce technology to stop reading as soon as possible). So much more IO intensive.

**Comment by ross-spencer** [comment]
I can confirm that it fails on the same file. I can't do any more analysis
on that file today, but can help narrow it down next week.

The second point, i think perhaps that is where we've been talking about
cross purposes in the other thread. To be as clear as possible - are you
saying because MD5 scans of the objects are more intensive, and in
combination with your recursive code (which naturally eats memory)...
there's not enough resource to go around causing a fail?

**Comment by richardlehane** [comment]
I don't think the recursive code matters here: it is still linear & there should still only be a single file open at any one time (you're not running with the -multi flag). The earlier recursion issue was caused by an infinite loop - this isn't happening here.

With MD5 on you are doing a lot more IO (doing full file reads, holding onto file handles longer): where you're already getting IO issues (all those winapi errors) I just think having MD5 on will exacerbate them. But the underlying issue may be elsewhere. 

E.g. I suspect one issue may be with the file.Close calls in sf: I'm not currently handling errors for these. You're encountering a lot of file.Open errors for this job and I bet there are probably file.Close errors silently happening too. Not handling these (either retrying or failing) will have the effect of leaking file handles which may then be causing your winapi #4 (too many files open) issues.

I'll do some win testing this weekend on large scans using the debugging tools described here:
[https://blogs.technet.microsoft.com/markrussinovich/2009/09/29/pushing-the-limits-of-windows-handles/](https://blogs.technet.microsoft.com/markrussinovich/2009/09/29/pushing-the-limits-of-windows-handles/).

Re. the specific file here: are you able to share it? Appreciate you might not (given [redacted]), but otherwise: what's the file size? Can you run comdump on it? (https://github.com/richardlehane/comdump) Comdump uses mscfb package too so should highlight any mscfb errors.

**Comment by richardlehane** [comment]
Hi Ross
I looked more closely at the relevant mscfb code: https://github.com/richardlehane/mscfb/blob/master/file.go#L80. I've tightened up the detection of cycles when navigating directories. This may have been the cause of your error (repeated memory allocation in an endless loop) - hard to tell without seeing the file. If this was indeed the bug, rebuilding fresh sf with this latest mscfb patch should give you a "mscfb: cycles detected" error.

**Comment by ross-spencer** [comment]
I think this is what you expected Richard: 

      filesize : 484352
      modified : 2000-10-02T12:51:06+13:00
      errors   : 'mscfb: directory entries sector cycle; 0'
      matches  :
        - id      : pronom
          puid    : fmt/111
          format  : 'OLE2 Compound Document Format'
          version :
          mime    :
          basis   : 'byte match at 0, 30'
          warning : 

Is this a cue to look at the file for something to fix?

**Comment by richardlehane** [comment]
Great that's it. Your ole file has an unusual directory chain. Where I'd expect either a valid next entry or end of chain value (0xffffffff) your file has 0.

Does this file open? Can you extract with other tools eg 7zip? If so, I may be being too strict with spec. If not, you might be able to fix by locating that value and changing to end of chain.

**Comment by ross-spencer** [comment]
Cool, so, we have the same output from comdump (probably expected) but that's a graceful fail. 

As for Apache POI - it crashes. 
7-Zip doesn't recognize it as a valid archive. 
OpenOffice / Word don't like it either. 

Looking in the file (I didn't have time running out of the door Friday) - it doesn't look right and so I'll have to do some investigation. For now, Siegfried will keep running through this collection, and so that's good enough. 

Thanks for the swift fix!
