### ISSUE TITLE
develop branch fails to build - issues with filepath package?

### ISSUE THREAD

**Issue by mistydemeo** [richardlehane/siegfried#70]
When trying to build the develop branch, I get the following errors:

```
# github.com/richardlehane/siegfried/cmd/sf
src/github.com/richardlehane/siegfried/cmd/sf/longpath.go:45: undefined: filepath in filepath.SkipDir
src/github.com/richardlehane/siegfried/cmd/sf/longpath.go:48: undefined: shortpath
src/github.com/richardlehane/siegfried/cmd/sf/longpath.go:55: undefined: filepath in filepath.Walk
```

The master branch works fine. I think I have all the dependencies installed correctly.

**Comment by richardlehane** [comment]
thanks for spotting Misty - fixed now: https://github.com/richardlehane/siegfried/commit/d5397a8ecf7a0c9394b8c2a36f93fb7085ede02b
