### ISSUE TITLE
Building Roy/Siegfried develop branch to test MIMEInfo

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#74]
Hi Richard,

Do you have any tips for building SF for testing MIMEInfo? - I've tika-mimetypes.xml in my user folder but am not seeing it appear in the -v output when i look in SF version. Can i take it for granted the signature file is built with this XML? 

Cheers,

Ross

**Comment by richardlehane** [comment]
ha ha! ... I've about a week's worth of bugfixing to go - so develop branch is **completely unstable** at the moment. Also I've done a bunch of bugfixing this morning so suggest fetching the very latest.

Freedestop sigs seem to be broken at the moment but I'm getting good results now from tika mimetypes. 

Process is:

1) make sure you have a tika-mimetypes.xml file in your $HOME/siegfried folder
2) then just do `roy build -mi tika`.

To get pronom/mimeinfo multi-identification you do: `roy build` and then `roy add -mi tika` (this adds the mimeinfo as a second identifier to the pronom identifier).

**Comment by ross-spencer** [comment]
Awesome. Thx Richard. The hope was just to have a look how it was going and what results I might see on some of our data - and if i could pass on anything constructive then that too; but recognize you're still a bit away. 

Looking forward to the addition, and another hope with my attempts this morning is to begin to think about how to incorporate the results in my analysis scripts - either a Golang port or an addition to the Python version - the additional ID a neat added value feature.

**Comment by richardlehane** [comment]
very happy for you to start playing with it now. It will hopefully be stable by mid-week (Weds) & that might be the point to start raising tickets for any issues you see, if you feel like doing some larger scale testing

**Comment by richardlehane** [comment]
[UPDATE] freedesktop.org signature files working now too!
These are available at: https://freedesktop.org/wiki/Software/shared-mime-info/

just do `roy build -mi freedesktop` to get working.

Can also do `roy build -mi freedesktop` && `roy add -mi tika` to do side-by-side freedesktop.org vs tika comparison.

**Comment by ross-spencer** [comment]
Just tried it on a single file so far but think that's all good!

      matches  :
        - ns      : pronom
          id      : fmt/40
          format  : 'Microsoft Word Document'
          version : '97-2003'
          mime    : 'application/msword'
          basis   : 'extension match doc; container name CompObj with byte match at 70, 20; name WordDocument with name only'
          warning : 
        - ns      : tika
          id      : 'application/msword'
          format  : 'Microsoft Word Document'
          mime    : 'application/msword'
          basis   : 'extension match doc; byte match at 0, 8 (signature 9/12); byte match at 0, 8 (signature 12/12)'
          warning : 
        - ns      : freedesktop
          id      : 'application/msword'
          format  : 'Word document'
          mime    : 'application/msword'
          basis   : 'extension match doc; byte match at 0, 4 (signature 11/11); byte match at 0, 8 (signature 10/11); byte match at 2108, 9 (signature 6/11)'
          warning : 

Thanks Richard.

**Comment by richardlehane** [comment]
With the commits pushed today, I think the develop branch is pretty much ready. I'll do some large scale testing over the weekend before merging with master. 
Closing this now but if you notice any bugs with latest develop - please raise new issues!
