### ISSUE TITLE
UFRaw MIMEInfo File

### ISSUE THREAD

**Issue by ross-spencer** [richardlehane/siegfried#82]
Hi Richard,

Just putting this here in case it is useful. The tool UFRAW also has a MIMEInfo file. It has limited number of binary signatures, but maybe some decent glob patterns and setting of priorities.

The MIMEInfo file is in the source. Most recent release is: https://sourceforge.net/projects/ufraw/files/ufraw/ufraw-0.22/ 

Figured it might be useful for one of your recipe pages and for future users. 

Cheers,

Ross

**Comment by richardlehane** [comment]
cool, thanks Ross. Have included this info on the Building Signatures wiki page: https://github.com/richardlehane/siegfried/wiki/Building-a-signature-file-with-ROY

(also the wiki is open for editing, so please do feel free to make changes there if you'd like)
