### ISSUE TITLE
pronom -noreports flag gives fmt/245 as extension match when no extension 

### ISSUE THREAD

**Issue by richardlehane** [richardlehane/siegfried#87]
If you build a PRONOM signature file using the -noreports flag, fmt/245 is gives an extension match for files e.g. README that do not have an extension.

If built with reports, this issue does not arise. cc @ross-spencer

**Comment by ross-spencer** [comment]
Doh! ^_^ 
Will have to be more thorough in signature generation in future. Will be sure to note use of -noreports mode in my analyses.

**Comment by richardlehane** [comment]
glad you did, otherwise would never have found this bug
